# Syntax reference for this file:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: pynssp documentation
on: [push, pull_request]

# https://gist.github.com/c-bata/ed5e7b7f8015502ee5092a3e77937c99
jobs:
  build-and-delpoy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/marketplace/actions/setup-python
      # ^-- This gives info on matrix testing.
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt && pip install sphinxcontrib-googleanalytics sphinx-copybutton
      - name: Build Sphinx docs
        run: |
          make docs

      # https://github.com/peaceiris/actions-gh-pages
      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          publish_dir: docs/_build/html/